#!/usr/bin/env bash
# QA v2 integration test: networking hostfwd reachability (PR #2 surface).
#
# Boots an Alpine guest with NIC args generated by `vmforge-net args`
# (networking/vmforge_net) including a hostfwd rule to guest SSH (port 22),
# then asserts the forwarded host port is reachable and serves an SSH banner.
#
# SKIPS (exit 0, with reason) until the networking subsystem (PR #2) is merged:
# the vmforge_net package does not exist on main yet.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SMOKE_DIR="$REPO_ROOT/qa/smoke"

if [[ ! -d "$REPO_ROOT/networking/vmforge_net" ]]; then
    echo "SKIP: networking/vmforge_net not present on this branch yet (waiting on PR #2 to merge)"
    exit 0
fi

BOOT_TIMEOUT="${BOOT_TIMEOUT:-300}"
WORKDIR="${WORKDIR:-$SCRIPT_DIR/.work}"
VM_MEM="${VM_MEM:-512}"
DRIVER="${DRIVER:-qemu}"
HOST_PORT="${HOST_PORT:-18022}"

mkdir -p "$WORKDIR"
SERIAL_LOG="$WORKDIR/serial-net-$$.log"
export WORKDIR SERIAL_LOG VM_MEM
SCRIPT_DIR="$SMOKE_DIR"
export SCRIPT_DIR

# shellcheck source=../smoke/drivers/qemu.sh
source "$SMOKE_DIR/drivers/$DRIVER.sh"

GUEST_IMAGE_URL="${GUEST_IMAGE_URL:-https://dl-cdn.alpinelinux.org/alpine/v3.20/releases/cloud/nocloud_alpine-3.20.3-x86_64-bios-cloudinit-r0.qcow2}"

cleanup() { vm_kill 2> /dev/null || true; }
trap cleanup EXIT

echo "==> Generating NIC args via vmforge-net (hostfwd tcp:127.0.0.1:$HOST_PORT->:22)"
NAT_JSON="$WORKDIR/nat.json"
cat > "$NAT_JSON" << EOF
{"port_forwards": ["tcp:127.0.0.1:$HOST_PORT-:22"]}
EOF
NET_ARGS="$(cd "$REPO_ROOT/networking" && python3 -m vmforge_net.cli args --config "$NAT_JSON" --format shell)"
echo "    args: $NET_ARGS"

cache="$WORKDIR/$(basename "$GUEST_IMAGE_URL")"
if [[ ! -s "$cache" ]]; then
    curl -fsSL --retry 3 --retry-delay 5 -o "$cache.tmp" "$GUEST_IMAGE_URL"
    mv "$cache.tmp" "$cache"
fi

SEED_DIR="$WORKDIR/seed"
mkdir -p "$SEED_DIR"
cat > "$SEED_DIR/user-data" << 'EOF'
#cloud-config
password: vmforge
chpasswd: { expire: false }
ssh_pwauth: true
packages: [openssh]
runcmd:
  - rc-service sshd start || service ssh start || true
  - echo VMFORGE_CLOUD_INIT_DONE > /dev/console
EOF
printf 'instance-id: vmforge-net\nlocal-hostname: vmforge-net\n' > "$SEED_DIR/meta-data"
SEED_ISO="$WORKDIR/seed.iso"
genisoimage -quiet -output "$SEED_ISO" -volid cidata -joliet -rock \
    "$SEED_DIR/user-data" "$SEED_DIR/meta-data"

DISK="$WORKDIR/net-$$.qcow2"
qemu-img create -q -f qcow2 -b "$cache" -F qcow2 "$DISK"

echo "==> Booting guest with generated NIC args"
QMP_SOCK="$WORKDIR/qmp-$$.sock"
# shellcheck disable=SC2046,SC2086
"$(qemu_bin)" $(_accel_args) $(_machine_args) \
    -m "$VM_MEM" -smp 1 \
    -drive "file=$DISK,if=virtio,format=qcow2" \
    -drive "file=$SEED_ISO,if=virtio,format=raw,media=cdrom,read-only=on" \
    $NET_ARGS \
    -display none -serial "file:$SERIAL_LOG" \
    -qmp "unix:$QMP_SOCK,server,nowait" &
QEMU_PID=$! # used by the sourced driver's vm_is_running/vm_kill
export QEMU_PID

vm_wait_ready "$BOOT_TIMEOUT" || { echo "FAIL: guest did not boot"; exit 1; }

echo "==> Waiting for SSH banner on 127.0.0.1:$HOST_PORT"
deadline=$((SECONDS + 120))
banner=""
while (( SECONDS < deadline )); do
    banner="$(timeout 5 bash -c "exec 3<>/dev/tcp/127.0.0.1/$HOST_PORT && head -c 32 <&3" 2> /dev/null || true)"
    [[ "$banner" == SSH-* ]] && break
    sleep 3
done
if [[ "$banner" == SSH-* ]]; then
    echo "PASS: forwarded port reachable, banner: $banner"
else
    echo "FAIL: no SSH banner via hostfwd port $HOST_PORT" >&2
    exit 1
fi
